background = 0xff162833
base = 0xff9BA4A1
text = 0xff8C9492
alternate_base = 0xff9BA4A1
bright_text = 0xff8C9492
accent = 0xffCDD3D5
accent_secondary = 0xffc4c9cc

h1_size = 22
h2_size = 17
h3_size = 14
font_size = 13
small_font_size = 11

icon_theme = "Papirus"
font_family = "Sans Serif"
font_family_monospace = "monospace"

rounding_large = 12
rounding_small = 8
