background = 0xff111316
base = 0xff8D6752
text = 0xff82593F
alternate_base = 0xff8D6752
bright_text = 0xff82593F
accent = 0xffC8B7B6
accent_secondary = 0xffc3c4c4

h1_size = 22
h2_size = 17
h3_size = 14
font_size = 13
small_font_size = 11

icon_theme = "Papirus"
font_family = "Sans Serif"
font_family_monospace = "monospace"

rounding_large = 12
rounding_small = 8
