background = 0xff102527
base = 0xff006778
text = 0xff005767
alternate_base = 0xff006778
bright_text = 0xff005767
accent = 0xff0095A5
accent_secondary = 0xffc3c8c9

h1_size = 22
h2_size = 17
h3_size = 14
font_size = 13
small_font_size = 11

icon_theme = "Papirus"
font_family = "Sans Serif"
font_family_monospace = "monospace"

rounding_large = 12
rounding_small = 8
