#!/bin/sh

WALLPAPER_DIR="$HOME/.wallpapers"

WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( \
    -iname "*.jpg" \
    -o -iname "*.png" \
    -o -iname "*.jpeg" \
    -o -iname "*.webp" \
\) | shuf -n 1)

set-wallpaper "$WALLPAPER"
